Added useSignInEmail hook and store universal email
0xsequence/kit pull request #181
Opened 2024-10-29 20:05 UTC by corbanbrook

2024-10-29 20:06 UTC, yigiterdev submitted a review, later dismissed

2024-10-30 14:51 UTC, SamueleA requested changes

2024-10-30 14:51 UTC, SamueleA commented on examples/react/src/components/Connected.tsx
> +  console.log('MY EMAIL', email)
Can we remove this log prior to merging?

2024-10-30 14:57 UTC, SamueleA commented on packages/kit/src/hooks/useSignInEmail.ts
> +    const storedEmail = await storage?.getItem(LocalStorageKey.WaasSignInEmail)
Do we want to rename the LocalStorageKey to remove the term "waas" from it and make it more general?

2024-10-30 14:57 UTC, corbanbrook commented on examples/react/src/components/Connected.tsx
> +  console.log('MY EMAIL', email)
done

2024-10-30 14:59 UTC, SamueleA approved these changes

2024-10-30 15:02 UTC, corbanbrook commented on packages/kit/src/hooks/useSignInEmail.ts
> +    const storedEmail = await storage?.getItem(LocalStorageKey.WaasSignInEmail)
We will leave it for now and migrate it another time.

2024-10-30 15:02 UTC, merged