Added sending unsponsored transaction to kit demo
0xsequence/kit pull request #186
Opened 2024-11-01 05:54 UTC by andrewlee348

2024-11-01 15:13 UTC, SamueleA submitted a review, later dismissed
LGTM!

2024-11-01 16:25 UTC, tolgahan-arikan commented
after talking with Andrew we decided to add sponsored call for Polygon as well (he is also adding one for Immutable) so that examples match in all available chains in demo. I'll put this in draft for now.

2024-11-01 17:25 UTC, andrewlee348 commented
I noticed that the next demo didnt have sponsored transaction testing so I added that while I was at it.

2024-11-06 20:46 UTC, SamueleA requested changes

2024-11-06 20:46 UTC, SamueleA commented on examples/next/src/app/components/Connected.tsx
> +      setLastTxnDataHash2((txnData2 as any).hash ?? txnData)
I think this should be based on the logic of the previous lines?
```
setLastTxnDataHash>>>3<<<((txnData>>>2<<< as any).hash ?? txnData>>>3<<<)
```

2024-11-06 20:46 UTC, SamueleA commented on examples/next/src/app/components/Connected.tsx
>        setLastTxnDataHash2((txnData2 as any).hash ?? txnData)
I think the variable after the ?? should be txnData2, right? (I know, I know this is technically not part of this PR XD)

2024-11-06 20:46 UTC, SamueleA commented on examples/react/src/components/Connected.tsx
> +      console.log('txnData3', txnData3)
Let's remove the console.logs that were added for developing only

2024-11-07 15:27 UTC, andrewlee348 commented on examples/next/src/app/components/Connected.tsx
> +      setLastTxnDataHash2((txnData2 as any).hash ?? txnData)
ahh, this was an oversight. The react one was right but I forgot to set it for the next component. Its fixed now

2024-11-12 18:03 UTC, SamueleA approved these changes

2024-11-12 18:33 UTC, merged