3627 remove isdev from exposed interface
0xsequence/kit pull request #193
Opened 2024-11-13 18:59 UTC by andrewlee348

2024-11-18 16:47 UTC, SamueleA requested changes
There are two improvement that I think would be necessary for this:

1. Can we use have the DEVMODE variable be read from an environment variable?

2. Can we remove the `isDev` parameter from the kitConfig and then replace instances in which isDev would normally be used with that DEVMODE variable?

https://github.com/0xsequence/kit/blob/master/packages/kit/src/types.ts#L78

2024-11-18 19:20 UTC, andrewlee348 commented
@SamueleA I must've forgotten to push my latest changes. I've removed all isDev from config and kit packages and added a workaround for env variables since the packages aren't able to read env variables from outside the packages folder.

2024-12-02 20:12 UTC, corbanbrook requested changes

2024-12-02 20:12 UTC, corbanbrook commented on scripts/generate-env.js
> +const fs = require('fs')
Should not generate an env file that overrides env.ts

2024-12-02 20:12 UTC, corbanbrook commented on scripts/generate-env.js
> +const fs = require('fs')
This would potentially get committed into the code base.

2024-12-02 20:12 UTC, corbanbrook commented on packages/kit/src/env.ts
> +export const DEVMODE = false
This file should simply reexport the process.env.DEVMODE

2024-12-02 20:12 UTC, corbanbrook commented on packages/kit/src/env.ts
> +export const DEVMODE = false
or process.env.DEVMODE should just be used directly instead

2024-12-02 21:20 UTC, corbanbrook commented
https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables

2025-01-07 16:02 UTC, closed without merging