Switching out old indexer api
0xsequence/kit pull request #196
Opened 2024-11-15 22:08 UTC by andrewlee348

2024-11-18 23:27 UTC, andrewlee348 commented
I'll remove the `//ATTENTION:` comments after as they might be useful later to change things before merge

2024-11-26 13:11 UTC, taylanpince commented
@andrewlee348 lgtm, we'll wait for @corbanbrook and @tolgahan-arikan 's reviews

Please remove the `ATTENTION` lines now, thank you

2025-01-13 21:46 UTC, corbanbrook requested changes
The changes look good overall but one thing to note is that the data hooks are publically exposed by the library. So this introduces breaking changes.

I think it would be good if we kept the hooks args the same as previously if possible.

2025-01-14 21:56 UTC, corbanbrook approved these changes

2025-01-14 22:27 UTC, merged