Checkout updates
0xsequence/kit pull request #20
Opened 2024-04-17 10:29 UTC by tolgahan-arikan

2024-04-18 19:09 UTC, taylanpince requested changes

2024-04-18 19:09 UTC, taylanpince commented on examples/react/src/utils/helpers.ts
> +      authToken: '', // TODO: remove, use token from api
This needs to be fetched from our internal API. We already have a Sardine token generation API that we use for Wallet.

2024-04-18 19:09 UTC, taylanpince commented on packages/checkout/src/api/data.tsx
> +  const response = await fetch(`https://api.sandbox.sardine.ai/v1/orders/${orderId}`, {
Should change to api.sardine.ai

2024-04-18 19:09 UTC, taylanpince commented on packages/checkout/src/views/CheckoutSelection/index.tsx
> +        const url = `https://crypto.sandbox.sardine.ai/?client_token=${response.clientToken}&show_features=true`
Should change to api.sardine.ai

2024-04-18 19:09 UTC, taylanpince commented on packages/checkout/src/api/data.tsx
> +  const response = await fetch('https://api.sandbox.sardine.ai/v1/auth/client-tokens', {
Should change to api.sardine.ai

2024-04-22 15:52 UTC, SamueleA commented on examples/react/src/utils/helpers.ts
> +  blockchainNftId: string,
Isn't this the same as the token Id?

2024-04-22 16:48 UTC, taylanpince commented on examples/react/src/utils/helpers.ts
> +  blockchainNftId: string,
@SamueleA Correct, this should be the tokenId

2024-04-22 17:28 UTC, SamueleA commented on examples/react/src/utils/helpers.ts
> +  blockchainNftId: string,
I just checked. This is the orderId. It's just named weirdly on sardine.

2024-04-22 17:30 UTC, SamueleA commented on packages/checkout/src/views/CheckoutSelection/index.tsx
> +        const url = `https://crypto.sandbox.sardine.ai/?client_token=${response.clientToken}&show_features=true`
About these two api calls (ie the one to create a sarding and the one to fetch the status of the order)
Should the sardine client token be kept secret? Because if yes, we shouldn't be making these two calls on the frontend, but rather the backend and we should create two corresponding backend endpoints to wrap them.

2024-04-22 18:50 UTC, taylanpince commented on examples/react/src/utils/helpers.ts
> +  blockchainNftId: string,
Ah thanks – That's really weird naming glad you checked.

2024-04-22 18:52 UTC, taylanpince commented on packages/checkout/src/views/CheckoutSelection/index.tsx
> +        const url = `https://crypto.sandbox.sardine.ai/?client_token=${response.clientToken}&show_features=true`
@SamueleA We already have [an endpoint here](https://github.com/0xsequence/stack/blob/29df2aba4aff0e7ae5d8b9a515953f61c5ddf229/api/proto/api.ridl#L395) – That's what I meant above, SDK should leverage this endpoint to get a client token, which can then be used in these requests. We've already tested this flow with Tolga.

2024-05-01 19:16 UTC, taylanpince approved these changes

2024-05-01 21:13 UTC, SamueleA commented
I'm having difficulty rebasing this PR with all the refactoring that occurred with the recent SSR changes. I'll port the changes into a branch that will be forked from master then close this PR

2024-05-02 15:45 UTC, SamueleA commented
Closing PR since I reduplicated these changes in a branch freshly forked from master

2024-05-02 15:45 UTC, closed without merging